---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git::https://github.com/jayanth-tjvrr/arlon-bc//bc1
configurations:
- configurations.yaml
patches:
  - target:
      group: controlplane.cluster.x-k8s.io
      version: v1beta1
      kind: MachineDeployment
      name: .*
    path: md-details.yaml

